-- 案例驱动的回归评测：将已发布案例转为确定性回归题，并记录运行与逐项结果
-- JSON 列表沿用既有迁移风格（如 rag_chat_messages.sources_json），使用 TEXT 存储序列化后的 JSON

CREATE TABLE case_regression_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  case_id BIGINT NOT NULL UNIQUE REFERENCES cases(id),
  query TEXT NOT NULL,
  expected_evidence TEXT,
  key_points TEXT,
  embedding_model VARCHAR(100),
  embedding_dimension INT,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE case_regression_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  started_at TIMESTAMP NOT NULL DEFAULT NOW(),
  finished_at TIMESTAMP,
  total_items INT NOT NULL DEFAULT 0,
  passed INT NOT NULL DEFAULT 0,
  failed INT NOT NULL DEFAULT 0,
  skipped INT NOT NULL DEFAULT 0,
  trigger_source VARCHAR(50),
  embedding_model VARCHAR(100),
  status VARCHAR(20) NOT NULL DEFAULT 'RUNNING'
);

CREATE TABLE case_regression_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id BIGINT NOT NULL REFERENCES case_regression_runs(id),
  -- 刻意不加外键 REFERENCES case_regression_items(id)：容忍历史运行结果在回归项变动（重建/删除）后仍留存
  item_id BIGINT NOT NULL,
  passed BOOLEAN NOT NULL DEFAULT FALSE,
  retrieved_evidence_ids TEXT,
  matched_key_points TEXT,
  missing_key_points TEXT,
  topk_snapshot TEXT,
  failure_reason TEXT
);

-- case_id 已由 UNIQUE 约束创建隐式唯一索引，无需再建单列索引
CREATE INDEX idx_case_regression_items_active ON case_regression_items(active);
CREATE INDEX idx_case_regression_results_run_id ON case_regression_results(run_id);
CREATE INDEX idx_case_regression_results_item_id ON case_regression_results(item_id);
