CREATE TABLE cases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  problem_description TEXT,
  root_cause TEXT,
  resolution_steps TEXT,
  resolution_result TEXT,
  affected_versions VARCHAR(500),
  environment VARCHAR(100),
  service VARCHAR(100),
  ai_generated_content TEXT,
  user_confirmed_content TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
  version_no INT NOT NULL DEFAULT 1,
  source_session_id BIGINT,
  source_message_id BIGINT,
  active BOOLEAN NOT NULL DEFAULT FALSE,
  created_by VARCHAR(100),
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE case_audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  case_id BIGINT NOT NULL REFERENCES cases(id),
  action VARCHAR(50) NOT NULL,
  previous_status VARCHAR(20),
  new_status VARCHAR(20),
  operator VARCHAR(100),
  remark TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_cases_status ON cases(status);
CREATE INDEX idx_cases_active ON cases(active);
CREATE INDEX idx_case_audit_logs_case_id ON case_audit_logs(case_id);
